set foreign_key_checks = 0;
truncate table ecom.accounts;
truncate table ecom.addresses;
truncate table ecom.book;
truncate table ecom.carts;
truncate table ecom.categories;
truncate table ecom.clothes;
truncate table ecom.comments;
truncate table ecom.customers;
truncate table ecom.items;
truncate table ecom.orders;
truncate table ecom.payment;
truncate table ecom.ratings;
truncate table ecom.ship_by_drone;
truncate table ecom.ship_by_road;
truncate table ecom.ship_by_sea;
truncate table ecom.shipments;
truncate table ecom.shoes;



INSERT INTO ecom.accounts (id, account_number, balance) VALUES (1, 'ACC1001', 1500.5);
INSERT INTO ecom.accounts (id, account_number, balance) VALUES (2, 'ACC1002', 3050.75);
INSERT INTO ecom.accounts (id, account_number, balance) VALUES (3, 'ACC1003', 250.25);
INSERT INTO ecom.accounts (id, account_number, balance) VALUES (4, 'ACC1004', 5020);
INSERT INTO ecom.accounts (id, account_number, balance) VALUES (5, 'ACC1005', 1000);
INSERT INTO ecom.addresses (id, city, state, street, zip_code) VALUES (1, 'New York', 'NY', '123 Elm St', '10001');
INSERT INTO ecom.addresses (id, city, state, street, zip_code) VALUES (2, 'Los Angeles', 'CA', '456 Maple Ave', '90001');
INSERT INTO ecom.addresses (id, city, state, street, zip_code) VALUES (3, 'Chicago', 'IL', '789 Oak St', '60601');
INSERT INTO ecom.addresses (id, city, state, street, zip_code) VALUES (4, 'Houston', 'TX', '321 Pine St', '77001');
INSERT INTO ecom.addresses (id, city, state, street, zip_code) VALUES (5, 'Phoenix', 'AZ', '654 Birch Rd', '85001');
INSERT INTO ecom.book (isbn, attribute, author, id_book, publisher, title, id) VALUES ('978-3-16-148410-0', 'Hardcover', 'George Orwell', 'BK001', 'Penguin', '1984', 1);
INSERT INTO ecom.book (isbn, attribute, author, id_book, publisher, title, id) VALUES ('978-0-7432-7356-0', 'Paperback', 'Harper Lee', 'BK002', 'Arrow Books', 'To Kill a Mockingbird', 2);
INSERT INTO ecom.book (isbn, attribute, author, id_book, publisher, title, id) VALUES ('978-1-56619-909-4', 'Ebook', 'F. Scott Fitzgerald', 'BK003', 'Scribner', 'The Great Gatsby', 3);
INSERT INTO ecom.book (isbn, attribute, author, id_book, publisher, title, id) VALUES ('978-0-452-28423-4', 'Audiobook', 'Herman Melville', 'BK004', 'Penguin Classics', 'Moby-Dick', 4);
INSERT INTO ecom.book (isbn, attribute, author, id_book, publisher, title, id) VALUES ('978-0-671-72525-8', 'Paperback', 'Mark Twain', 'BK005', 'Signet Classics', 'The Adventures of Huckleberry Finn', 5);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('ac100002-92e0-1210-8192-e0c270830000', 1, 2, null, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('ac100002-92e0-1471-8192-e0f4fcd00000', 1, 1, null, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('ac100002-92e0-1668-8192-e0c67a6c0000', 1, 3, null, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('ac100002-92e0-175d-8192-e0c78c190000', 1, 4, null, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('ac100002-92e0-175d-8192-e0c798360001', 1, 4, null, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('ac100002-92e0-175d-8192-e0c79d8f0002', 1, 3, null, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('CART002', 2, 4, 1, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('CART003', 3, 1, 2, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('CART004', 4, 5, 4, null);
INSERT INTO ecom.carts (id_cart, customer_id, item_id, payment_id, order_id) VALUES ('CART005', 5, 3, 5, null);
INSERT INTO ecom.categories (id, name) VALUES (1, 'Fiction');
INSERT INTO ecom.categories (id, name) VALUES (2, 'Non-Fiction');
INSERT INTO ecom.categories (id, name) VALUES (3, 'Electronics');
INSERT INTO ecom.categories (id, name) VALUES (4, 'Clothing');
INSERT INTO ecom.categories (id, name) VALUES (5, 'Accessories');
INSERT INTO ecom.categories (id, name) VALUES (6, 'Book');
INSERT INTO ecom.clothes (color, size, id) VALUES ('Red', 'M', 1);
INSERT INTO ecom.clothes (color, size, id) VALUES ('Blue', 'L', 2);
INSERT INTO ecom.clothes (color, size, id) VALUES ('Green', 'S', 3);
INSERT INTO ecom.clothes (color, size, id) VALUES ('Black', 'XL', 4);
INSERT INTO ecom.clothes (color, size, id) VALUES ('White', 'M', 5);
INSERT INTO ecom.comments (id, content, customer_id, item_id) VALUES (1, 'Great product!', 1, 1);
INSERT INTO ecom.comments (id, content, customer_id, item_id) VALUES (2, 'Very satisfied', 2, 3);
INSERT INTO ecom.comments (id, content, customer_id, item_id) VALUES (3, 'Would buy again', 3, 5);
INSERT INTO ecom.comments (id, content, customer_id, item_id) VALUES (4, 'Not what I expected', 4, 4);
INSERT INTO ecom.comments (id, content, customer_id, item_id) VALUES (5, 'Excellent quality', 5, 2);
INSERT INTO ecom.customers (id, first_name, last_name, middle_name, account_id, address_id) VALUES (1, 'John', 'Doe', 'A', 1, 2);
INSERT INTO ecom.customers (id, first_name, last_name, middle_name, account_id, address_id) VALUES (2, 'Jane', 'Smith', null, 2, 3);
INSERT INTO ecom.customers (id, first_name, last_name, middle_name, account_id, address_id) VALUES (3, 'Alice', 'Johnson', null, 3, 4);
INSERT INTO ecom.customers (id, first_name, last_name, middle_name, account_id, address_id) VALUES (4, 'Michael', 'Brown', 'B', 4, 1);
INSERT INTO ecom.customers (id, first_name, last_name, middle_name, account_id, address_id) VALUES (5, 'Sarah', 'Davis', null, 5, 5);
INSERT INTO ecom.items (item_type, id, name, price, category_id, product_image) VALUES ('BOOK', 1, '1984', 9.99, 6, 'https://picsum.photos/seed/1420/1000');
INSERT INTO ecom.items (item_type, id, name, price, category_id, product_image) VALUES ('BOOK', 2, 'To Kill a Mockingbird', 7.99, 6, 'https://picsum.photos/seed/2874/1000');
INSERT INTO ecom.items (item_type, id, name, price, category_id, product_image) VALUES ('CLOTHES', 3, 'Red Shirt', 19.99, 4, 'https://picsum.photos/seed/3111/1000');
INSERT INTO ecom.items (item_type, id, name, price, category_id, product_image) VALUES ('CLOTHES', 4, 'Blue Jeans', 29.99, 4, 'https://picsum.photos/seed/4933/1000');
INSERT INTO ecom.items (item_type, id, name, price, category_id, product_image) VALUES ('SHOES', 5, 'Nike Sneakers', 59.99, 5, 'https://picsum.photos/seed/5334/1000');
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (2, '2024-10-05', 'Processing', 'CART002', 1, 1, 3);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (3, '2024-10-08', 'Delivered', 'CART003', 1, 2, 1);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (4, '2024-10-10', 'Canceled', 'CART004', 4, 5, 4);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (5, '2024-10-12', 'Shipped', 'CART005', 5, 4, 5);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (6, null, 'Pending', 'ac100002-92e0-1210-8192-e0c270830000', 1, 6, 6);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (7, null, 'Pending', 'ac100002-92e0-1668-8192-e0c67a6c0000', 1, 7, 7);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (8, null, 'Pending', 'ac100002-92e0-175d-8192-e0c78c190000', 1, 8, 8);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (9, null, 'Pending', 'ac100002-92e0-175d-8192-e0c798360001', 1, 9, 9);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (10, null, 'Pending', 'ac100002-92e0-175d-8192-e0c79d8f0002', 1, 10, 10);
INSERT INTO ecom.orders (id, order_date, status, cart_id, customer_id, payment_id, shipment_id) VALUES (11, null, 'Pending', 'ac100002-92e0-1471-8192-e0f4fcd00000', 1, 11, 11);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 1, 3050.75, 'Visa', '4111111111111111', '12/2024', '1234567890', null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CASH', 2, 1000, null, null, null, '9876543210', 1000);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 4, 5020, 'Discover', '6011000000000000', '09/2025', '4445556666', null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 5, 250.25, 'American Express', '340000000000009', '03/2024', '7778889999', null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 6, 0, null, null, null, null, null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 7, 0, null, null, null, null, null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 8, 0, null, null, null, null, null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 9, 0, null, null, null, null, null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 10, 0, null, null, null, null, null);
INSERT INTO ecom.payment (payment_type, id, amount, method, card_number, expiration_date, phone_number, cash_received) VALUES ('CARD', 11, 0, null, null, null, null, null);
INSERT INTO ecom.ratings (id, rating_value, author_id, item_id) VALUES (1, 5, 1, 3);
INSERT INTO ecom.ratings (id, rating_value, author_id, item_id) VALUES (2, 4, 2, 4);
INSERT INTO ecom.ratings (id, rating_value, author_id, item_id) VALUES (3, 3, 3, 5);
INSERT INTO ecom.ratings (id, rating_value, author_id, item_id) VALUES (4, 2, 4, 1);
INSERT INTO ecom.ratings (id, rating_value, author_id, item_id) VALUES (5, 5, 5, 2);
INSERT INTO ecom.ship_by_drone (flight_duration, id) VALUES (2.5, 5);
INSERT INTO ecom.ship_by_drone (flight_duration, id) VALUES (0, 6);
INSERT INTO ecom.ship_by_drone (flight_duration, id) VALUES (0, 7);
INSERT INTO ecom.ship_by_drone (flight_duration, id) VALUES (0, 8);
INSERT INTO ecom.ship_by_drone (flight_duration, id) VALUES (0, 9);
INSERT INTO ecom.ship_by_drone (flight_duration, id) VALUES (0, 10);
INSERT INTO ecom.ship_by_drone (flight_duration, id) VALUES (0, 11);
INSERT INTO ecom.ship_by_road (delivery_duration, id) VALUES (4.8, 4);
INSERT INTO ecom.ship_by_sea (ship_name, id) VALUES ('SS Atlantic', 1);
INSERT INTO ecom.ship_by_sea (ship_name, id) VALUES ('SS Arctic', 3);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (1, 'FedEx', 'Delivered', '1234567890', null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (3, 'DHL', 'In Transit', '1122334455', null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (4, 'USPS', 'Delivered', '2233445566', null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (5, 'Amazon Logistics', 'Out for Delivery', '3344556677', null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (6, null, null, null, null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (7, null, null, null, null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (8, null, null, null, null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (9, null, null, null, null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (10, null, null, null, null);
INSERT INTO ecom.shipments (id, carrier, status, tracking_number, address) VALUES (11, null, null, null, null);
INSERT INTO ecom.shoes (brand, id) VALUES ('Nike', 1);
INSERT INTO ecom.shoes (brand, id) VALUES ('Adidas', 2);
INSERT INTO ecom.shoes (brand, id) VALUES ('Puma', 3);
INSERT INTO ecom.shoes (brand, id) VALUES ('Reebok', 4);
INSERT INTO ecom.shoes (brand, id) VALUES ('Under Armour', 5);